//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vt_BraunAppEntities : DbContext
    {
        public vt_BraunAppEntities()
            : base("name=vt_BraunAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vt_Conversions> vt_Conversions { get; set; }
        public virtual DbSet<vt_Deductions> vt_Deductions { get; set; }
        public virtual DbSet<vt_Depreciation> vt_Depreciation { get; set; }
        public virtual DbSet<vt_LinkSecurity> vt_LinkSecurity { get; set; }
        public virtual DbSet<vt_Log> vt_Log { get; set; }
        public virtual DbSet<vt_MarkUp> vt_MarkUp { get; set; }
        public virtual DbSet<vt_Pages> vt_Pages { get; set; }
        public virtual DbSet<vt_QuoteConversions> vt_QuoteConversions { get; set; }
        public virtual DbSet<vt_QuoteDeduction> vt_QuoteDeduction { get; set; }
        public virtual DbSet<vt_Quotes> vt_Quotes { get; set; }
        public virtual DbSet<vt_Roles> vt_Roles { get; set; }
        public virtual DbSet<vt_SubDeductions> vt_SubDeductions { get; set; }
        public virtual DbSet<vt_UserPermissions> vt_UserPermissions { get; set; }
        public virtual DbSet<vt_UserProfile> vt_UserProfile { get; set; }
    }
}
