//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_Conversions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vt_Conversions()
        {
            this.vt_QuoteConversions = new HashSet<vt_QuoteConversions>();
            this.vt_QuoteDeduction = new HashSet<vt_QuoteDeduction>();
        }
    
        public int ID { get; set; }
        public string ConversionName { get; set; }
        public string Type { get; set; }
        public string Company { get; set; }
        public Nullable<int> Year { get; set; }
        public string Description { get; set; }
        public string Make { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> DealerPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string VisualCode { get; set; }
        public string EpicorCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_QuoteConversions> vt_QuoteConversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_QuoteDeduction> vt_QuoteDeduction { get; set; }
    }
}
