//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_Log
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ViewName { get; set; }
        public string MethodName { get; set; }
        public string Message { get; set; }
        public Nullable<bool> isException { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual vt_UserProfile vt_UserProfile { get; set; }
    }
}
