//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_QuoteDeduction
    {
        public int ID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> ConversionID { get; set; }
        public Nullable<int> DeductionID { get; set; }
        public Nullable<decimal> ConversionAmount { get; set; }
        public Nullable<double> DepreciatedAmount { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual vt_Conversions vt_Conversions { get; set; }
        public virtual vt_Deductions vt_Deductions { get; set; }
        public virtual vt_Quotes vt_Quotes { get; set; }
    }
}
