//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_Quotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vt_Quotes()
        {
            this.vt_QuoteConversions = new HashSet<vt_QuoteConversions>();
            this.vt_QuoteDeduction = new HashSet<vt_QuoteDeduction>();
        }
    
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string SearchType { get; set; }
        public string SearchTypeID { get; set; }
        public string Make { get; set; }
        public Nullable<int> MakeID { get; set; }
        public string Model { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> YearID { get; set; }
        public string Trim { get; set; }
        public Nullable<int> TrimID { get; set; }
        public Nullable<decimal> CurrentMilage { get; set; }
        public string StateCode { get; set; }
        public Nullable<decimal> CleanTrade { get; set; }
        public Nullable<decimal> AverageTrade { get; set; }
        public Nullable<decimal> RoughTrade { get; set; }
        public Nullable<decimal> RetailTrade { get; set; }
        public string MarkUpPercent { get; set; }
        public string MarkUpFixed { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> TotalConversionDeduction { get; set; }
        public string VinNumber { get; set; }
        public string RegionVal { get; set; }
        public string RegionText { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public Nullable<bool> IsClean { get; set; }
        public Nullable<bool> IsAverage { get; set; }
        public Nullable<bool> IsRough { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_QuoteConversions> vt_QuoteConversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vt_QuoteDeduction> vt_QuoteDeduction { get; set; }
    }
}
