//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_SubDeductions
    {
        public int ID { get; set; }
        public Nullable<int> DeductionID { get; set; }
        public string DeductionDetail { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual vt_Deductions vt_Deductions { get; set; }
    }
}
