//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bruneability_Portal.NadaLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTokenRequest", Namespace="http://webservice.nada.com/")]
    [System.SerializableAttribute()]
    public partial class GetTokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.nada.com/", ConfigurationName="NadaLogin.SecureLoginSoap")]
    public interface SecureLoginSoap {
        
        // CODEGEN: Generating message contract since element name tokenRequest from namespace http://webservice.nada.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.nada.com/getToken", ReplyAction="*")]
        Bruneability_Portal.NadaLogin.getTokenResponse getToken(Bruneability_Portal.NadaLogin.getTokenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.nada.com/getToken", ReplyAction="*")]
        System.Threading.Tasks.Task<Bruneability_Portal.NadaLogin.getTokenResponse> getTokenAsync(Bruneability_Portal.NadaLogin.getTokenRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getToken", Namespace="http://webservice.nada.com/", Order=0)]
        public Bruneability_Portal.NadaLogin.getTokenRequest1Body Body;
        
        public getTokenRequest1() {
        }
        
        public getTokenRequest1(Bruneability_Portal.NadaLogin.getTokenRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.nada.com/")]
    public partial class getTokenRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bruneability_Portal.NadaLogin.GetTokenRequest tokenRequest;
        
        public getTokenRequest1Body() {
        }
        
        public getTokenRequest1Body(Bruneability_Portal.NadaLogin.GetTokenRequest tokenRequest) {
            this.tokenRequest = tokenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTokenResponse", Namespace="http://webservice.nada.com/", Order=0)]
        public Bruneability_Portal.NadaLogin.getTokenResponseBody Body;
        
        public getTokenResponse() {
        }
        
        public getTokenResponse(Bruneability_Portal.NadaLogin.getTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.nada.com/")]
    public partial class getTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTokenResult;
        
        public getTokenResponseBody() {
        }
        
        public getTokenResponseBody(string getTokenResult) {
            this.getTokenResult = getTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecureLoginSoapChannel : Bruneability_Portal.NadaLogin.SecureLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecureLoginSoapClient : System.ServiceModel.ClientBase<Bruneability_Portal.NadaLogin.SecureLoginSoap>, Bruneability_Portal.NadaLogin.SecureLoginSoap {
        
        public SecureLoginSoapClient() {
        }
        
        public SecureLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecureLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bruneability_Portal.NadaLogin.getTokenResponse Bruneability_Portal.NadaLogin.SecureLoginSoap.getToken(Bruneability_Portal.NadaLogin.getTokenRequest1 request) {
            return base.Channel.getToken(request);
        }
        
        public string getToken(Bruneability_Portal.NadaLogin.GetTokenRequest tokenRequest) {
            Bruneability_Portal.NadaLogin.getTokenRequest1 inValue = new Bruneability_Portal.NadaLogin.getTokenRequest1();
            inValue.Body = new Bruneability_Portal.NadaLogin.getTokenRequest1Body();
            inValue.Body.tokenRequest = tokenRequest;
            Bruneability_Portal.NadaLogin.getTokenResponse retVal = ((Bruneability_Portal.NadaLogin.SecureLoginSoap)(this)).getToken(inValue);
            return retVal.Body.getTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bruneability_Portal.NadaLogin.getTokenResponse> Bruneability_Portal.NadaLogin.SecureLoginSoap.getTokenAsync(Bruneability_Portal.NadaLogin.getTokenRequest1 request) {
            return base.Channel.getTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bruneability_Portal.NadaLogin.getTokenResponse> getTokenAsync(Bruneability_Portal.NadaLogin.GetTokenRequest tokenRequest) {
            Bruneability_Portal.NadaLogin.getTokenRequest1 inValue = new Bruneability_Portal.NadaLogin.getTokenRequest1();
            inValue.Body = new Bruneability_Portal.NadaLogin.getTokenRequest1Body();
            inValue.Body.tokenRequest = tokenRequest;
            return ((Bruneability_Portal.NadaLogin.SecureLoginSoap)(this)).getTokenAsync(inValue);
        }
    }
}
